development:
  access_key_id: <%= ENV["AWS_ACCESS_KEY_ID_DEV"] %>
  secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY_DEV"] %> 

production:
  access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %> 
