## All database credentials should be provided by environment variables.

development: &default
  adapter: postgis
  encoding: utf8
  database: dogbeaches_dev
  username: <%= ENV["POSTGRES_USERNAME"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  su_username: <%= ENV["POSTGRES_SU"] %>
  su_password: <%= ENV["POSTGRES_SU_PASSWORD"] %>
  host: <%= ENV["POSTGRES_HOST"] %>

test:
  <<: *default
  adapter: postgis
  encoding: utf8
  database: dogbeaches_test

production:
  <<: *default
  adapter: postgis
  encoding: utf8
  database: dogbeaches
